<?php include_once('header.php');?>

<?php
$banner_image = "images/about/top-banner.webp";
$banner_title = "Privacy Policy";
include_once('banner.php');
?>


        <!--------------------------------- faq ------------------------------->

    <section class="w-[80%] max-[1024px]:w-[90%] mx-auto py-16 max-[1024px]:py-10">
        <div class="">
            <p class="text-[#939393]"><strong class="text-black">("WWW.HALADRIVE.AE")</strong> online privacy policy ("Policy"). This policy applies only to activities <strong class="text-black">WWW.HALADRIVE.AE</strong> engages in this on its website and does not apply to WWW.HALADRIVE.AE activities that are "offline" or unrelated to the website.</p>
            <p class="text-[#939393] mt-4">The website WWW.HALADRIVE.AE gathers some anonymous information about how visitors use the site. This data is acquired to improve the website's functionality but does not individually identify users by itself or in conjunction with other data. The WWW.HALADRIVE.AE website may gather anonymous data about you, such as the kind of browser you are using and the duration of your visit. The WWW.HALADRIVE.AE website may also ask you for personally identifiable information, such as your name, address, phone number, and email address, when you provide WWW.HALADRIVE.AE comments or emails, register for services, or purchase via the website; this information may be collected. You always have the choice to provide us with personally identifying information in these situations.</p>
            <p class="text-[#939393] mt-4">DISCLOSURE AND USE OF INFORMATION. Except as expressly noted below, we do not share any personally identifiable data about you that we may have about you with third parties. Instead, our site uses the data it gathers to process orders, keep you updated on the progress of your orders, let you know about new items or limited-time deals that may be of interest to you, and run statistical analyses to help us make our site better. To process your check or money order properly, fulfill your purchase, enhance the functioning of our website, deliver your order, and send you promotional communications from us, we may also release your Personal information to third parties. For instance, in order for the delivery provider to deliver the things you bought, we must disclose your postal address.</p>
            <p class="text-[#939393] mt-4">No personally identifying information related to credit/debit cards will be kept, sold, shared, rented, or leased to any third parties. Cookies are discrete pieces of data that a user's browser caches. Cookies are used by WWW.HALADRIVE.AE to detect whether you have previously visited the home page. Nevertheless, no further user data is acquired. In order to improve how well our website functions or to determine which portions of our website are most popular, WWW.HALADRIVE.AE may utilize anonymous "aggregated data." Also, with your consent, WWW.HALADRIVE.AE may publish your user name or other identifying information if you submit work for publication or comments.</p>
            <p class="text-[#939393] mt-4">Moreover, WWW.HALADRIVE.AE may provide personally identifiable data in response to a subpoena, court order, or other similar processes. Such personally identifiable information may also be provided by WWW.HALADRIVE.AE in response to a request from a law enforcement agency or as otherwise required by law. If WWW.HALADRIVE.AE declares bankruptcy or if there is a transfer of ownership or the assets of WWW.HALADRIVE.AE, in conjunction with planned or completed corporate reorganizations, such as mergers or acquisitions, your personally identifiable information may be disclosed to a party.</p>
            <p class="text-[#939393] mt-4">SECURITY. In accordance with the law, WWW.HALADRIVE.AE takes the necessary precautions to safeguard data security and privacy, using a variety of hardware and software techniques. Unfortunately, WWW.HALADRIVE.AE is unable to ensure the safety of any data shared online.</p>
            <p class="text-[#939393] mt-4">OTHER WEBSITES. WWW.HALADRIVE.AE is not responsible for the privacy practices of third-party websites to which it connects. Different guidelines for collecting and using your personal information may apply if you provide any information to such third parties. Before giving them any information, we firmly advise you to study the privacy policies of such third parties. The actions or policies of third parties are not subject to our control. Please be advised that our websites may include links to third-party-owned and -operated websites on the Internet. This Policy does not apply to the privacy policies of Web sites that are connected to our site. These other websites could send users their own cookies or clear GIFs, gather information, or ask for personally identifying data. This data collection is beyond our control. If you have any concerns about how these organizations use the information they gather, you should get in touch with them directly.</p>
            <p class="text-[#939393] mt-4">MINORS. Underage children's personal information is not deliberately collected by WWW.HALADRIVE.AE. The WWW.HALADRIVE.AE website and services are not intended for use by children and WWW.HALADRIVE.AE specifically asks that minors under the age of 18 not submit any personal information to the website. WWW.HALADRIVE.AE does not intentionally release confidential information about kids under the age of 18 since it does not collect information on them. Please email info@haladrive.ae if you desire to change or amend any information that WWW.HALADRIVE.AE has received it.</p>
            <p class="text-[#939393] mt-4">CHANGES TO THE PRIVACY POLICY. WWW.HALADRIVE.AE. The Website Policies and Terms & Conditions may be modified or amended from time to time to comply with standards and regulations. Consumers are thus urged to frequent these parts often in order to stay informed about updates to the website. Changes will take effect on the day they are posted."</p>
        </div>
    </section>

    <!--------------------------------- footer ------------------------------->

<?php include_once('footer.php');?>